name: Build_firmware_master-custom

on:
  workflow_dispatch:

# Ensures that only one deploy task per branch/environment will run at a time.
concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  base-images:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        variant:
          - tasmota
          - tasmota--slowpwm
#          - tasmota4M
          - tasmota-minimal
#          - tasmota-display
#          - tasmota-ir
          - tasmota-ir--nomodulation
#          - tasmota-knx
#          - tasmota-lite
          - tasmota-sensors
#          - tasmota-zbbridge
#          - tasmota-zigbee
          - tasmota32
          - tasmota32--slowpwm
          - tasmota32-webcam
#          - tasmota32-bluetooth
#          - tasmota32-display
#          - tasmota32-ir
#          - tasmota32-lvgl
          - tasmota32c3
#          - tasmota32solo1
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master-custom
      - name: Set up Python
        uses: actions/setup-python@v1
      - name: Install dependencies
        run: |
          pip install -U platformio
      - name: Run PlatformIO
        run: platformio run -e ${{ matrix.variant }}
      - uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: ./build_output
          retention-days: 1
