name: Build_firmware_master-custom

on:
  workflow_dispatch:

# Ensures that only one deploy task per branch/environment will run at a time.
concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  base-images:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        variant:
          - tasmota
          - tasmota--slowpwm
          - tasmota2M
          - tasmota4M
#          - tasmota-debug
          - tasmota-minimal
#          - tasmota-display
#          - tasmota-ir
#          - tasmota-ir--nomodulation
          - tasmota2M-ir--nomodulation
#          - tasmota-knx
#          - tasmota-lite
          - tasmota-sensors
          - tasmota2M-sensors
#          - tasmota-zbbridge
#          - tasmota-zigbee
          - tasmota32
          - tasmota32--slowpwm
#          - tasmota32-zbbrdgpro
          - tasmota32-webcam
#          - tasmota32-bluetooth
#          - tasmota32-nspanel
#          - tasmota32-display
#          - tasmota32-ir
#          - tasmota32-lvgl
          - tasmota32c3
#          - tasmota32c3cdc
#          - tasmota32s2
#          - tasmota32s2cdc
#          - tasmota32s3
#          - tasmota32s3cdc
#          - tasmota32solo1
#          - tasmota32solo1-safeboot
#          - tasmota32-safeboot
#          - tasmota32c3-safeboot
#          - tasmota32c3cdc-safeboot
#          - tasmota32s2-safeboot
#          - tasmota32s2cdc-safeboot
#          - tasmota32s3-safeboot
#          - tasmota32s3cdc-safeboot
#          - tasmota32-odroidgo
#          - tasmota32-core2

    steps:
      - uses: actions/checkout@v3
        with:
          ref: master-custom
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -U platformio
      - name: Run PlatformIO
        run: platformio run -e ${{ matrix.variant }}
      - uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: ./build_output
          retention-days: 1
